# Generated by Django 5.0.1 on 2024-01-31 02:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_profile_count_follower_profile_facebook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='catergry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('text', models.TextField(max_length=10000)),
                ('img', models.ImageField(upload_to='blog/')),
                ('views', models.IntegerField(default=0)),
                ('count_likes', models.IntegerField(default=0)),
                ('Created_At', models.DateTimeField(default=datetime.datetime.now, verbose_name='Created At')),
                ('likes', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('catergryy', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.catergry')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('Created_At', models.DateTimeField(default=datetime.datetime.now, verbose_name='Created At')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
